# Generated by Django 4.2.1 on 2023-06-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
