# Generated by Django 4.2.1 on 2023-06-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes_enrolled', to='lmsAdmin.user'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='classes_taught', to='lmsAdmin.user'),
        ),
    ]
